/* ============================================
   UAE Schools List
   ============================================ */

// List of imaginary UAE schools
const UAE_SCHOOLS = [
    // Dubai Schools
    'Al Noor International School - Dubai',
    'Dubai Modern Academy',
    'Emirates International School - Dubai',
    'GEMS Wellington Academy - Dubai',
    'Greenfield International School - Dubai',
    'Jumeirah English Speaking School',
    'Kings\' School Dubai',
    'Nord Anglia International School - Dubai',
    'Raffles World Academy - Dubai',
    'Repton School Dubai',
    'Sunmarke School - Dubai',
    'The English College Dubai',
    'The International School of Choueifat - Dubai',
    'Universal American School - Dubai',
    
    // Abu Dhabi Schools
    'Al Yasmina Academy - Abu Dhabi',
    'American Community School - Abu Dhabi',
    'British International School - Abu Dhabi',
    'Cranleigh Abu Dhabi',
    'GEMS American Academy - Abu Dhabi',
    'International School of Choueifat - Abu Dhabi',
    'Raha International School - Abu Dhabi',
    'The British School Al Khubairat - Abu Dhabi',
    'The Sheikh Zayed Private Academy - Abu Dhabi',
    'Yasmina British Academy - Abu Dhabi',
    
    // Sharjah Schools
    'Al Diyafah High School - Sharjah',
    'American School of Creative Science - Sharjah',
    'GEMS Cambridge International School - Sharjah',
    'Sharjah English School',
    'The International School of Choueifat - Sharjah',
   'AL Ahliah Charity Pvt. School',
'Al Ahliah Pvt. Schools LLC.',
'Al Amaal English High School (PVT)',
'Al Amal School For The Deaf',
'Al Amana Private School',
'Al Ansar int.pvt.School',
'AL ANSAR NATIONAL PVT SCHOOL',
'Al Basaier Pvt. School',
'Al Bayan National School',
'Al Bayan Pvt.School',
'Al Choueifat Int. School',
'Al Delta English School LLC.',
'Al Dhaid Pvt. School',
'AL DHIA AL SCIENTIFIC PRIVATE SCHOOL LLC',
'AL DURRAH INTERNATIONAL SCHOOL LLC',
'Al Falah Private School',
'Al Istiqlal Private School L.L.C',
'Al Itqan American School Pvt',
'Al Kamal American Private NT School',
'Al Marifa Int. Private School (American)',
'Al Marifa Int. Private School (G.C.S.E)',
'Al Mawahib British Pvt. School',
'Al Murooj (Pvt) Eng. Kindergarten & School',
'Al Mustaqbal Pvt. School',
'AL Najma Private School.LLC.',
'Al Noor Int. School L.L.C',
'Al Qemah Private School',
'Al Resalah American International School LLC',
'Al Resalah International private School of Science LLC',
'Al Rowad British private school',
'Al Rushed American Private School',
'Al Sabah Indian Pvt. School',
'AL SALEH PRIVATE SCHOOL FOR GIRLS',
'Al Shola Pvt. School LLC',
'AL TAFAWQ PRIVATE SCHOOL',
'AL ULLA PRIVATE SCHOOL LLC.',
'Al Wahda (P.V.T)  School LLC',
'Al Zehour Private School LLC',
'Alsedra Private School',
'Ambassador School LLC',
'American Gulf School L.L.C',
'American Private School of Kalba',
'American School of Creative Science Pvt.',
'Amity Pvt. School LLC',
'Aspam Indian Int.  Pvt. School. LLC',
'Australian International Pvt. School',
'Beaconhouse Al Khaleej International School LLC',
'Bhavans Pearl Wisdom School L.L.C',
'Bin Khaldun Pvt. School',
'Brilliant Int. Private School',
'Cloud British Pvt. School',
'Darb Al Saada Private School',
'Delhi Pvt.School LLC.',
'East Coast Eng school',
'ELITE SCHOOL.LLC',
'Emirates American School',
'Emirates National School',
'Emirates National Schools',
'EMIRATES PRIVATE SCHOOL L.L.C',
'ENGLISH PRIVATE SCHOOL OF KALBA',
'Far Eastern Pvt.School',
'French International Private School - SHJ ',
'Gems Cambridge International Private School Sharjah ',
'Gems Millennium Private School',
'Gems Westminster School Sharjah LLC',
'German INT. School Sharjah',
'Gulf Asian English Schools LLC',
'Happy Home Eng. School L.L.C',
'Ibn Seena English High School L.L.C.',
'India International School LLC',
'Indian Excellent Pvt. School',
'International School of Creative Science Pvt',
'Khalifah Al Hamza American Private School - L - L.L.C - S.P',
'Leaders Private School',
'Manarat Al Sharjah Private School. LLC',
'Manthena American School L.L.C',
'Masar Private School L.L.C',
'New Indian Model School ',
'Nibras Al Iman Pvt. School LLC',
'Our Own English High School',
'Pace British School L.L.C',
'Pace International School LLC',
'Pakistan Islamia Higher Secondary School -SHJ.LLC',
'Pamir Private School L.L.C S.P',
'Private School of Scientific Innovation',
'Progressive Eng. School LLC',
'Providence English Private School',
'Radiant Indian School for Girls & Boys',
'Rosary School LLC',
'Ryan Intl. Priv. School',
'Sabis International Private School LLC- Aljada',
'Salman al farsi school',
'Sama American Private School',
'Scholars Int. Academy Pvt. School. LLC',
'School of Knowledge LLC.',
'Sharjah American Int. Pvt. School',
'Sharjah English School  ',
'Sharjah Indian Private School - Branch',
'Sharjah Indian School',
'Sharjah Public School & Childrens Pabilion',
'Shj. British Int .Pvt. School  ',
'Shj. British Int .Pvt. School (American)',
'SHJ. INT. PVT. SCHOOL (British)',
'SHJ. INT. PVT. SCHOOL (MoE)',
'SHJ.PVT.SCHOOL.',
'Spring dale Indian School LLC',
'Sunaa Al ghad School L.L.C',
'Taryam American Private School',
'The City School International PVT L.L.C',
'THE HOPE ENGLISH SCHOOL L.L.C-S.P',
'The Modern American Int. Pvt. School L.L.C',
'The New Filipino Pvt School LLC',
'Victoria English Pvt. School LLC',
'Victoria Int. shj . School',
'VICTORIA INT. SHJ . SCHOOL PROPRITORSHIP L.L.C (KALBA)',
'Wes green Int. Pvt. School. LLC',

    
    // Ajman Schools
    'Ajman Academy',
    'GEMS Cambridge International School - Ajman',
    'International School of Choueifat - Ajman',
    
    // Ras Al Khaimah Schools
    'Al Hamra Academy - Ras Al Khaimah',
    'GEMS Westminster School - Ras Al Khaimah',
    'Ras Al Khaimah Academy',
    
    // Fujairah Schools
    'Fujairah Private Academy',
    'GEMS Cambridge International School - Fujairah',
    
    // Umm Al Quwain Schools
    'Umm Al Quwain Academy',
    'GEMS Cambridge International School - Umm Al Quwain',
    
    // Other Notable Schools
    'Al Ain Academy',
    'Al Bateen Academy - Abu Dhabi',
    'Al Ittihad Private School - Abu Dhabi',
    'Al Mamoura Academy - Abu Dhabi',
    'Al Muna Academy - Abu Dhabi',
    'Al Mushrif School - Abu Dhabi',
    'Al Rayana School - Abu Dhabi',
    'Al Yasat Private School - Abu Dhabi',
    'Brighton College Abu Dhabi',
    'Cranleigh School Abu Dhabi',
    'Deira International School - Dubai',
    'Dubai British School',
    'Dubai College',
    'Dubai English Speaking College',
    'Dubai International Academy',
    'Dubai Scholars Private School',
    'GEMS Dubai American Academy',
    'GEMS Founders School - Dubai',
    'GEMS Metropole School - Dubai',
    'GEMS Our Own English High School - Dubai',
    'GEMS Wellington International School - Dubai',
    'GEMS Winchester School - Dubai',
    'Jebel Ali School - Dubai',
    'Jumeirah College - Dubai',
    'Kings\' School Al Barsha - Dubai',
    'Kings\' School Nad Al Sheba - Dubai',
    'Nord Anglia International School - Dubai',
    'Raffles International School - Dubai',
    'Swiss International Scientific School - Dubai',
    'The Arbor School - Dubai',
    'The Aquila School - Dubai',
    'The British School - Dubai',
    'The Cambridge High School - Abu Dhabi',
    'The Indian High School - Dubai',
    'The Millennium School - Dubai',
    'The School of Research Science - Dubai',
    'The Westminster School - Dubai',
    'Victory Heights Primary School - Dubai',
    'Wellington International School - Dubai'
];

// Export for use in other files
if (typeof window !== 'undefined') {
    window.UAE_SCHOOLS = UAE_SCHOOLS;
}

